### PR TITLE
19 action mint burn on allowed users

### LINKED ISSUE #19: Action MINT / BURN on allowed users
Try to MINT / BURN on allowed wallet

The transaction should failed if user is not eligible

### PR DESCRIPTION
**Pull request by Antopablo**
## 🧩 Pull Request Type
Please select the type that best describes your changes:

- [x] 🚀 Feature
- [x] 🐛 Bug Fix
- [x] 💡 Improvement / Refactor
- [ ] 🧰 Chore / Maintenance
- [ ] 🧾 Documentation Update
- [ ] ⚡ Hotfix / Critical Patch

---

## 📝 Description
- Can mint / burn on allowed wallet
- Fix nb_decimal for mint/burn
---

## 🧪 Testing

- [x] Tested locally
- [ ] Unit tests added / updated
- [ ] CI actions pass successfully
- [x] Manual verification done

---

## 🔗 Related Issues

[Link](https://github.com/TookenOrg/tooken-services/issues/19)

---

## 🎯 Target Branch
- [x] `develop` (integration)
- [ ] `main` (release)

---

## 🧭 Checklist

Before submitting, make sure you’ve checked the following:

- [x] PR title follows convention (`feat:`, `fix:`, `docs:`, etc.)
- [x] Code follows project guidelines and formatting
- [x] All tests pass (`go test`, `npm test`, etc.)
- [x] No secrets or sensitive data in commits

### CODE REVIEW

File: internal/blockchain/services/burn_token.go [hunk 1]
```diff
@@ -14,13 +15,18 @@ import (
...
-	ok := controlInputBurn(tokenAddr, to, humanAmount)
+	tokenInfos, err := database.GetTokenByAddress(ctx, tokenAddr)
+	if err != nil {
+		return
+	}
+
+	ok := controlInputMint(tokenAddr, to, humanAmount, tokenInfos.NbDecimal)
 	if !ok {
-		err = errors.New("Input data for burn are incorrect")
+		err = errors.New("Input data for mint are incorrect")
```
Comment (Antopablo) [inline internal/blockchain/services/burn_token.go]: incorrect
